(()=>{'use strict';
const {PDFDocument,StandardFonts,degrees,rgb}=PDFLib;let sourceBytes=null,order=[],rotations=[],annotations=[],name='document.pdf';
const $=id=>document.getElementById(id), status=(m,e=false)=>{$('pdfStatus').textContent=m;$('pdfStatus').classList.toggle('error',e);};
function parsePages(text,max){const out=new Set();for(const raw of text.split(',')){const s=raw.trim();if(!s)continue;if(/^\d+$/.test(s)){const n=+s;if(n>=1&&n<=max)out.add(n-1);}else{const m=s.match(/^(\d+)\s*-\s*(\d+)$/);if(m){let a=+m[1],b=+m[2];if(a>b)[a,b]=[b,a];for(let n=a;n<=b;n++)if(n>=1&&n<=max)out.add(n-1);}}}return [...out].sort((a,b)=>a-b);}
async function loadOne(file){if(!file)return;try{sourceBytes=await file.arrayBuffer();const d=await PDFDocument.load(sourceBytes);order=[...Array(d.getPageCount()).keys()];rotations=order.map(()=>0);annotations=[];name=file.name.replace(/\.pdf$/i,'')+'-edited.pdf';$('pdfEditor').hidden=false;$('downloadPdf').disabled=false;render();status(`Loaded ${file.name}: ${order.length} page${order.length===1?'':'s'}.`);}catch(e){console.error(e);status('Could not open that PDF. Encrypted/password-protected PDFs may not be supported.',true);}}
function render(){const box=$('pdfPages');box.innerHTML='';order.forEach((original,pos)=>{const d=document.createElement('div');d.className='pdf-page';d.innerHTML=`<strong>Page ${pos+1}</strong><span class="small">Original page ${original+1}${rotations[pos]?` • rotated ${rotations[pos]}°`:''}</span><div class="page-controls"><button title="Move left/up">↑</button><button title="Move right/down">↓</button></div>`;const [up,down]=d.querySelectorAll('button');up.disabled=pos===0;down.disabled=pos===order.length-1;up.onclick=()=>move(pos,-1);down.onclick=()=>move(pos,1);box.appendChild(d);});$('annotPage').max=Math.max(1,order.length);}
function move(i,delta){const j=i+delta;if(j<0||j>=order.length)return;[order[i],order[j]]=[order[j],order[i]];[rotations[i],rotations[j]]=[rotations[j],rotations[i]];annotations.forEach(a=>{if(a.pos===i)a.pos=j;else if(a.pos===j)a.pos=i;});render();}
async function build(indices=null){const src=await PDFDocument.load(sourceBytes),out=await PDFDocument.create(),idx=indices||order.map((_,i)=>i);const originals=idx.map(i=>order[i]);const copied=await out.copyPages(src,originals);for(let k=0;k<copied.length;k++){const p=copied[k],pos=idx[k];const base=p.getRotation().angle||0;p.setRotation(degrees((base+rotations[pos])%360));out.addPage(p);}const font=await out.embedFont(StandardFonts.Helvetica);for(const a of annotations){const newPos=idx.indexOf(a.pos);if(newPos<0)continue;out.getPage(newPos).drawText(a.text,{x:a.x,y:a.y,size:a.size,font,color:rgb(.12,.16,.14)});}return new Blob([await out.save()],{type:'application/pdf'});}
$('pdfFile').onchange=e=>loadOne(e.target.files[0]);$('mergeFiles').onchange=async e=>{const files=[...e.target.files];if(files.length<2){status('Choose two or more PDFs to merge.',true);return;}try{const out=await PDFDocument.create();let total=0;for(const f of files){const src=await PDFDocument.load(await f.arrayBuffer());const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p));total+=pages.length;}downloadBlob('merged.pdf',new Blob([await out.save()],{type:'application/pdf'}));status(`Merged ${files.length} PDFs (${total} pages) and downloaded merged.pdf.`);}catch(err){console.error(err);status('Could not merge one or more of those PDFs.',true);}e.target.value='';};
$('downloadPdf').onclick=async()=>{if(!sourceBytes)return;try{downloadBlob(name,await build());status('Downloaded the edited PDF.');}catch(e){console.error(e);status('Could not build the edited PDF.',true);}};
$('extractPages').onclick=async()=>{const sel=parsePages($('pageSelection').value,order.length);if(!sel.length){status('Enter pages to extract, for example 1-3, 5.',true);return;}downloadBlob('extracted-pages.pdf',await build(sel));status(`Extracted ${sel.length} page${sel.length===1?'':'s'}.`);};
$('rotatePages').onclick=()=>{const sel=parsePages($('pageSelection').value,order.length);if(!sel.length){status('Enter the pages you want to rotate.',true);return;}sel.forEach(i=>rotations[i]=(rotations[i]+90)%360);render();status(`Rotated ${sel.length} selected page${sel.length===1?'':'s'} 90°.`);};
$('deletePages').onclick=()=>{const sel=parsePages($('pageSelection').value,order.length);if(!sel.length){status('Enter the pages you want to delete.',true);return;}if(sel.length>=order.length){status('A PDF must keep at least one page.',true);return;}for(const i of [...sel].sort((a,b)=>b-a)){order.splice(i,1);rotations.splice(i,1);annotations=annotations.filter(a=>a.pos!==i).map(a=>({...a,pos:a.pos>i?a.pos-1:a.pos}));}render();status(`Deleted ${sel.length} page${sel.length===1?'':'s'} from the working copy.`);};
$('addAnnotation').onclick=()=>{const pos=+$('annotPage').value-1,text=$('annotText').value.trim();if(pos<0||pos>=order.length||!text){status('Choose a valid page and enter annotation text.',true);return;}annotations.push({pos,text,x:+$('annotX').value||0,y:+$('annotY').value||0,size:+$('annotSize').value||12});$('annotText').value='';status(`Added text annotation to page ${pos+1}. It will appear in the downloaded PDF.`);};
$('clearPdf').onclick=()=>{sourceBytes=null;order=[];rotations=[];annotations=[];$('pdfEditor').hidden=true;$('downloadPdf').disabled=true;$('pdfFile').value='';status('No PDF loaded.');};
})();
